#!/usr/bin/env bash
# Script by https://github.com/exoess

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <position> <size>"
    exit 1
fi

open_window() {
    hyprctl dispatch exec "[move $(echo $1 | sed 's/,/ /'); size $(echo $2 | sed 's/x/ /')] foot"
}

open_window "$1" "$2"
