#!/usr/bin/env bash
# Script by https://github.com/exoess

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <position> <size> <window>"
    exit 1
fi

open_window() {
    hyprctl dispatch exec "[float; move ${1/,/ }; size ${2/x/ }] $3"
}

open_window "$1" "$2" "$3"
