#!/bin/bash

run() {
    if ! pgrep -f "$1" ;
    then
        "$@"&
    fi
}

run "swww" init
run "ags"
run "nm-applet"
run "blueman-applet"
run "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
run "fcitx5"
